// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
